### Common

server:
  port: 8100

spring:
  application:
    name: need-doctors
  profiles:
    active: pgsql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: "classpath:/db.changelog/db.changelog-master.yml"
    enabled: true


logging:
  level:
    root: INFO


---

logging:
  level:
    com.chumbok: DEBUG
    org.springframework.security: DEBUG


---

logging:
  level:
    com.chumbok: DEBUG

---


### PgSQL profile

spring:
  profiles: pgsql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/need-doctors-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12211221}


---

### Debug profile

spring:
  profiles: debug

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

---

